resources:
- name: myFirstRepo
  type: GitRepo
  configuration:
    # SCM integration where the repository is located
    gitProvider: Github
    # Repository path, including org name/repo name
    path: xafaghyujier/sasa
    branches:
      # Specifies which branches will trigger dependent steps
      include: main
      
- name: myPropertyBag
  type: PropertyBag
  configuration:
    commitSha: 1
    runID: 1
    
pipelines:
  - name: my_first_pipeline
    steps:
      - name: p1_s1
        type: Bash
        configuration:
          inputResources:
            - name: myFirstRepo
        execution:
          onExecute:
            - lscpu
