
pipelines:
  - name: my_first_pipeline
    steps:
      - name: p1_s1
        type: Bash
        configuration:
          inputResources:
            - name: myFirstRepo
        execution:
          onExecute:
            - lscpu
