name : sama
on : [push]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: malinskiy/action-android/install-sdk@release/0.1.2
      - run: sdkmanager platform-tools
      - run: adb devices
      - run: echo $ANDROID_HOME
